# Site settings
title: Fumes
subtitle: Art. Photography. Ideas.
photography_subtitle: The Camera as a Microphone
email: fumesmag@gmail.com
description: Online art magazine from South East Asia. Fumes project was started by two photographers in 2008.
projectimage: assets/i/t/fumesyousuck_thumb.png
license: CC0

# The current release of Fumes Project website
version: v3.11.1

# Site owner
owner:
  name: Fumes
  email: fumesmag@gmail.com
  link: https://fumes.junglestar.org
  twitter: fumesvoice
  facebook: fumesmagazine
  github: fumes
  google:
    plus: #username
    analytics: UA-16659805-1
    verify: google32e66f1a5601ec40

# BUILD SETTINGS
baseurl: ""
url: https://fumes.junglestar.org
sass:
  sass_dir: _sass
  style: :expanded # To minify use :compressed
#excerpt_separator: <!--more-->
#permalink: /:categories/:title/


# collect for me please...
collections:
  - socialicons

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - gulpfile.js
  - package.json
  - DS_Store
  - Icon
  - node_modules
  - uploads
  - rakefile


defaults:
  -
   scope:
     type: pages
   values:
     permalink: /:path/:basename:output_ext
  -
   scope:
     type: posts
   values:
     permalink: /:categories/:title/


gems:
  - jekyll-feed

  - jekyll-sitemap

  # https://github.com/danbee/jekyll-video-tag
  - jekyll_video_tag

  # https://github.com/wildlyinaccurate/jekyll-responsive-image
  # this one throw error so i just use plugin.rb instead of gem!
  # - [jekyll/responsive_image]

  # put back jekyll-tag gem. or use  _plugins/categories_tags_generator.rb!
  # http://geoexamples.com/other/2015/06/04/Jekyll-tags-plugin-gh-pages.html


## ADDONS / PLUGINS /.rb

#------------RESPONSIVE IMAGE
#https://github.com/wildlyinaccurate/jekyll-responsive-image
responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive_image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 70

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 960
      quality: 50
    - width: 1260

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images.
  #
  # Parameters available are:
  #   %{basename}  Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}  Basename without extension (assets/some-file.jpg => some-file)
  #   %{extension} Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}     Width of the resized image
  #   %{height}    Height of the resized image
  #
  output_path_format: assets/i/%{width}/%{basename}
