# Site settings
title: Fumes
subtitle: Art. Photography. Ideas.
photography_subtitle: The Camera as a Microphone
email: fumesmag@gmail.com
description: Online Art magazine covering mostly Asia Pacific. Fumes project was started by two photographers in 2010. Non-profit.
projectimage: assets/i/t/fumesyousuck_thumb.png
license: CC0
qr: yes

# The current release of Fumes Project website
version: 4.1.0

# Site owner
owner:
  name: Fumes
  email: fumesmag@gmail.com
  link: https://fumes.junglestar.org #maybe redundant
  twitter: "https://twitter.com/fumesvoice"
  facebook: "https://web.facebook.com/fumesmagazine"
  youtube:
  github: "https://github.com/fumes"
  google:
    analytics: UA-16659805-1
    verify: google32e66f1a5601ec40

# BUILD SETTINGS
baseurl: ""
url: https://fumes.junglestar.org
sass:
  sass_dir: _sass
  style: :expanded # To minify use :compressed
#excerpt_separator: <!--more-->
#permalink: /:categories/:title/


# collect for me please...
collections:
  - socialicons

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - gulpfile.js
  - package.json
  - .DS_Store
  - Icon
  - node_modules
  - uploads
  - rakefile


defaults:
  -
   scope:
     type: pages
   values:
     permalink: /:path/:basename:output_ext
  -
   scope:
     type: posts
   values:
     permalink: /:categories/:title/


plugins:
 - jekyll/tagging
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer
 - liquid_reading_time
 - jekyll-responsive-image #https://github.com/wildlyinaccurate/jekyll-responsive-image



tag_page_layout: post_index_tag
tag_page_dir: ./
tag_permalink_style: pretty
ignored_tags:


## ADDONS / PLUGINS /.rb

#------------RESPONSIVE IMAGE
#https://github.com/wildlyinaccurate/jekyll-responsive-image
responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive_image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 70

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 480  # [Required] How wide resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 960
      quality: 50
    - width: 1260

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images.
  #
  # Parameters available are:
  #   %{basename}  Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}  Basename without extension (assets/some-file.jpg => some-file)
  #   %{extension} Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}     Width of the resized image
  #   %{height}    Height of the resized image
  #
  output_path_format: assets/i/%{width}/%{basename}
