# Site settings
title: Fumes
subtitle: The Camera as a Microphone
email: fumesmag@gmail.com
description: Fumes project was started by two photographers. A metaphor to play with, delivering ideas via images.
projectimage: assets/i/t/fumesyousuck_thumb.png
license: CC0

# The release of Fumes Project that you're using
version: v3.7.2

# Site owner
owner:
  name: Fumes
  avatar_url: 
  email: fumesmag@gmail.com
  link: http://fumes.junglestar.org
  disqus-shortname:
  twitter: fumesvoice
  facebook: fumesmagazine
  github: fumes
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  soundcloud: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: UA-16659805-1
    verify: google32e66f1a5601ec40
    ad-client:
    ad-slot: 
  bing-verify:


# BUILD SETTINGS

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

###>OLD ( http://toybreaker.github.io/fumes/ )
url: http://fumes.github.io #dev url: "http://fumes.dev"

sass:
  sass_dir: _sass
  style: :expanded # To minify use :compressed

excerpt_separator: <!--more-->

# keep consistent with old g-indexed (seo!dude...) permalink structure
permalink: /:categories/:title/

# collect for me please...
collections:
 - socialicons

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
  - gulpfile.js
  - package.json
  - DS_Store
  - Icon
  - node_modules
  - uploads
  - rakefile


gems: 
- jekyll-sitemap

# https://github.com/danbee/jekyll-video-tag
- jekyll_video_tag 

# this one throw error so i just use plugin.rb instead of gem!
#- jekyll-responsive_image 

# put back jekyll-tag gem. or use  _plugins/categories_tags_generator.rb!
# http://geoexamples.com/other/2015/06/04/Jekyll-tags-plugin-gh-pages.html


## ADDONS / PLUGINS /.rb

#------------RESPONSIVE IMAGE
#https://github.com/wildlyinaccurate/jekyll-responsive-image
responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive_image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 70

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 960
      quality: 50
    - width: 1260

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images.
  #
  # Parameters available are:
  #   %{basename}  Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}  Basename without extension (assets/some-file.jpg => some-file)
  #   %{extension} Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}     Width of the resized image
  #   %{height}    Height of the resized image
  #
  output_path_format: assets/i/%{width}/%{basename}

















#### ------------ COMPLETE defaults list. ------------ ####
# --- useful to override stuff

# # Where things are
# source:      .
# destination: ./_site
# plugins:     ./_plugins
# layouts:     ./_layouts
# data_source: ./_data
# collections: null

# # Handling Reading
# safe:         false
# include:      [".htaccess"]
# exclude:      []
# keep_files:   [".git", ".svn"]
# encoding:     "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# # Filtering Content
# show_drafts: null
# limit_posts: 0
# future:      true
# unpublished: false

# # Plugins
# whitelist: []
# gems:      []

# # Conversion
# markdown:    kramdown
# highlighter: rouge
# lsi:         false
# excerpt_separator: "\n\n"

# # Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: "" # does not include hostname

# # Outputting
# permalink:     date
# paginate_path: /page:num
# timezone:      null

# quiet:    false
# defaults: []

# # Markdown Processors
# rdiscount:
#   extensions: []

# redcarpet:
#   extensions: []

# kramdown:
#   auto_ids:       true
#   footnote_nr:    1
#   entity_output:  as_char
#   toc_levels:     1..6
#   smart_quotes:   lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false

#   coderay:
#     coderay_wrap:              div
#     coderay_line_numbers:      inline
#     coderay_line_number_start: 1
#     coderay_tab_width:         4
#     coderay_bold_every:        10
#     coderay_css:               style
